print("Hi my dear frien!:3", end="\n")
print("Welcome to my program, It will remove all repetitions from your list", end="\n")
print("But firstly you must write your list", end="\n")
print("You should put enter agter writing your symbols")
print("You can write different symbols", end="\n")
print("Good luck!:3", end="\n")
Yourlist=input("Enter your symbols:").split(" ")
YourSrlist=list(set(Yourlist))
print(YourSrlist)